language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - async-test-support

install:
  - sudo apt-get install libev-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install luasocket
  - sudo luarocks install copas
  - sudo luarocks install lua-ev
  - git clone git://github.com/Olivine-Labs/say.git
  - cd say
  - sudo luarocks make
  - cd ../
  - git clone git://github.com/Olivine-Labs/luassert.git
  - cd luassert
  - sudo luarocks make
  - cd ../

script: "./install_and_test.sh"

notifications:
  email:
    on_success: always
    on_failure: always